dataset: "cifar100"
data_dir: "./dataset/data_folder/cifar100"

model_name: "module_small_patch16_224"
num_experts: 6
expert_depth: 2
expert_hidden_ratio: 0.10
gate_k: 2
pretrained: true
pretrained_model_path: "checkpoint/learn/cifar100_random_10_module_s_16/cifar100_random_10_module_s_16_epoch_50.pt"

unlearn_algo: "module_unlearn_algo"
unlearn_setting: "random"
forget_ratio: 0.10
alpha: 1.0
beta: 1.0
gamma: 1.0
eta: 1.0
k_u: 2

epochs: 50
batch_size: 32
lr: 3.0e-2
fa_threshold: 0.8
seed: 42