dataset: "pacs"
data_dir: "./dataset/data_folder/pacs"

model_name: "resnet18"
pretrained: false
pretrained_model_path: "checkpoint/learn/pacs_resnet18.pt" 

unlearn_algo: "ga"
forget_classes: [0, 1]  

batch_size: 32
lr: 0.0001
epochs: 1000
fa_threshold: 0.05 
seed: 42

